### ISSUE TITLE
For GCP SQL Database Instance, root_password always displaying as "Empty" even if the root user password is set while creating the  instance.

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-gcp#140]
- Create MYSQL database Instance with setting a password
- But `root_password` field is always showing as empty

6.1.1 Ensure that a MySQL database instance does not allow anyone to connect with administrative privileges (Scored).
**Description**
It is recommended to set a password for the administrative user (root by default) to
prevent unauthorized access to the SQL database instances.
This recommendation is applicable only for MySQL Instances. PostgreSQL does not offer
any setting for No Password from the cloud console.

**Comment by debabrat-git** [comment]
again did a another round of testing, it seems even if we have the root_password is set, we are showing as "Empty". But can it be possible to show in encrypted format instead of empty.

**Comment by Paulami30** [comment]
RootPassword information is not returned by the api requests, hence we are unable to add this column in the table.
