### ISSUE TITLE
Add a column or modify existing column in `gcp_compute_disk` table to store "Customer-supplied encryption key"

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-gcp#174]
**Is your feature request related to a problem? Please describe.**
Currently when a disk is encrypted with `customer-supplied` key it is not storing/displaying in column `disk_encryption_kms_key`.

**Describe the solution you'd like**
For the below example query used is
```
select
  name,
  disk_encryption_kms_key
from
  gcp_compute_disk
where
  name = 'disk-1-customer-supplied'

+--------------------------+-------------------------+
| name                     | disk_encryption_kms_key |
+--------------------------+-------------------------+
| disk-1-customer-supplied |                         |
+--------------------------+-------------------------+
```

**Additional context**
![image](https://user-images.githubusercontent.com/43408569/115222054-f0c26400-a127-11eb-9d12-8e77be4844a9.png)
![image](https://user-images.githubusercontent.com/43408569/115222121-033c9d80-a128-11eb-8ee8-68a6b37aacf6.png)

**Comment by anisadas** [comment]
DuplicatePR:https://github.com/turbot/steampipe-plugin-gcp/issues/175
