### ISSUE TITLE
Type might be incorrect for column `id`  in table  `gcp_compute_disk`. 

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-gcp#218]
**Describe the bug**
It is storing a value like `4.529625599075632e+18`  which seems incorrect to me.

**Steampipe version (`steampipe -v`)**
Example: v0.5.2

**Plugin version (`steampipe plugin list`)**
GCP: v0.13.0

**To reproduce**

**Expected behavior**

**Additional context**
![image](https://user-images.githubusercontent.com/43408569/121880482-b215e800-cd2b-11eb-965a-e1470d891aa8.png)

**Comment by ParthaI** [comment]
Unable to replicate the issue below is the list of disks which id column is looks good to me, so closing this issue.

![image](https://user-images.githubusercontent.com/47887552/122054506-5f106380-ce05-11eb-816f-530a56c6fe70.png)

**Comment by debabrat-git** [comment]
disk-1 id is `8239576662407829672` it is getting rounded up to what you mentioned above.
disk-1-test-002 id is `4529625599075632176`.
disk-1-unused id is  `4617633086743200852`

**Comment by debabrat-git** [comment]
![image](https://user-images.githubusercontent.com/43408569/122059322-20c97300-ce0a-11eb-8f20-9869e6e23c6a.png)
![image](https://user-images.githubusercontent.com/43408569/122059400-38086080-ce0a-11eb-8fed-328fa29ffc3e.png)
