### ISSUE TITLE
Add a column in gcp_sql_database  table to store `created time stamp` and `last updated time stamp` for database

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-gcp#233]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/operations#Operation

**Comment by misraved** [comment]
Closing the issue since it is not on priority.
