### ISSUE TITLE
List projects hydrate function fails when using application default credentials

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-gcp#289]
**Describe the bug**
After logging in with application default credentials, I ran `select * from gcp_project`, which then threw the error:
```
> select * from gcp_project
Error: rpc error: code = Internal desc = hydrate function listGCPProjects failed with panic runtime error: invalid memory address or nil pointer dereference
```

**Steampipe version (`steampipe -v`)**
v0.7.0

**Plugin version (`steampipe plugin list`)**
gcp v0.15.0

**To reproduce**
- Setup gcloud default config in `~/.config/gcloud/configurations/config_default`
- Authenticate by running `gcloud auth application-default login`
- Assign `Owner` permissions to your user in the project
- Run the query

**Expected behavior**
The query should list my projects

**Additional context**

**Comment by bigdatasourav** [comment]
@cbruno10 I have followed the below - It is working for me. please suggest if I miss anything or need to check it in different way.
all commented in .spc file. 
gcloud config set project project-name
gcloud auth application-default login

```
> select * from gcp_project
+------------+------------+----------------+-----------------+---------------------+--------------------------------------+--------+------------+--------+--------------------------------------------------
| name       | project_id | project_number | lifecycle_state | create_time         | parent                               | labels | title      | tags   | akas                                             
+------------+------------+----------------+-----------------+---------------------+--------------------------------------+--------+------------+--------+--------------------------------------------------
| parker-aaa | parker-aaa | 979620418102   | ACTIVE          | 2019-05-22 12:08:03 | {"id":"12258536632","type":"folder"} | <null> | parker-aaa | <null> | ["gcp://cloudresourcemanager.googleapis.com/proje
+------------+------------+----------------+-----------------+---------------------+--------------------------------------+--------+------------+--------+--------------------------------------------------

```

**Comment by rajlearner17** [comment]
@cbruno10 can you check if this error comes again for you? I don't see this. If good we can close this.
