### ISSUE TITLE
Add table `gcp_cloudrun_service`

### ISSUE THREAD

**Issue by slagathorr** [turbot/steampipe-plugin-gcp#341]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

Be able to list out metadata around Cloud Run deployed services.

https://cloud.google.com/run/docs/reference/rest#rest-resource:-v1.namespaces.services

**Comment by rajlearner17** [comment]
@slagathorr Appreciate trying out Steampipe. 
We will definitely look into this. 
Do you use `Steampipe` now for any use-case and particularly looking for this table? What query do you have in mind to use? This information will help us when we start designing and prioritizing the same. Thanks for the issue.

**Comment by slagathorr** [comment]
We are looking to analyze our entire deployment against billing data, and exploring using Steampipe to access the deployment data. We use Cloud Run quite frequently, so having access to this will be helpful.

**Comment by rajlearner17** [comment]
@slagathorr FYI, we are still checking how we can bring this, already engaged with the [GCP support](https://issuetracker.google.com/issues/224584846?pli=1). We will keep posted.
