### ISSUE TITLE
Fix integration tests for the GCP tables

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-gcp#367]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Closed as per - https://github.com/turbot/steampipe-plugin-gcp/pull/384
