### ISSUE TITLE
Using Workload Identity to Authenticate

### ISSUE THREAD

**Issue by anjuls** [turbot/steampipe-plugin-gcp#392]
**Is your feature request related to a problem? Please describe.**
As a user, I want to make my steampipe containers more secure and use the workload identity (GKE) feature to authenticate the service account instead of JSON keys.

**Describe the solution you'd like**
Enable workload identity used in GKE. 

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by cbruno10** [comment]
Hey @anjuls , I’m afraid that I'm not very familiar with how to use workload identities to authenticate with GCP APIs, but do you use any of those today for authentication with the gcloud CLI?

One option with the GCP plugin today for authentication is to use [Application Default Credentials](https://cloud.google.com/sdk/gcloud/reference/auth/application-default), so if you can use workload identities with the gcloud CLI, authenticating with the GCP plugin may just work once that’s configured, without the need for a service account key.
