### ISSUE TITLE
Is it possible to run steampipe on Google cloud shell without the credential file ?

### ISSUE THREAD

**Issue by Rstar1998** [turbot/steampipe-plugin-gcp#393]
So currently the only way steampipe can access cloud data is via the credential json file as per the docs 
```
1. Credentials from the json file specified by the credentials parameter in your steampipe config.
2. Credentials from the json file specified by the GOOGLE_APPLICATION_CREDENTIALS environment variable.
3. Credentials from the default json file location (~/.config/gcloud/application_default_credentials.json).
``` 
Is there any way to run steampipe on Google cloud shell without the credential file ( assuming cloud shell has all the access ) ?

**Comment by jchrisfarris** [comment]
Good morning Rstar1998 - Steampipe will use the default credentials available in the Google CloudShell. We've documented how to do that here: https://steampipe.io/docs/reference/integrations/gcp_cloudshell.

The GCP plugin is built on the Go libraries, and will use the google [Application Default Credentials](https://cloud.google.com/docs/authentication#adc). We'll make sure to update the documentation to reflect that. 

Let us know if you run into any other issues with running in the Cloud Shell

**Comment by cbruno10** [comment]
Thanks for linking to that great article @jchrisfarris !

@Rstar1998 , I'm closing this issue for now, but if you have anything else, please let us know!
