### ISSUE TITLE
Exponential back-off to handle HTTP/429 `RATE_LIMIT_EXCEEDED` condition ?

### ISSUE THREAD

**Issue by vmdude** [turbot/steampipe-plugin-gcp#441]
**Describe the bug**
When querying a lot of GCP projects, we're always throttled due to `RATE_LIMIT_EXCEEDED`:

```plain
	googleapi: Error 429: Quota exceeded for quota metric 'List projects V1' and limit 'List projects V1 per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:XXX'.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/XXX",
      "quota_limit": "ListProjectsV1RequestsPerMinutePerProject",
      "quota_limit_value": "240",
      "quota_location": "global",
      "quota_metric": "cloudresourcemanager.googleapis.com/list_projects_v1_requests",
      "service": "cloudresourcemanager.googleapis.com"
    },
    "reason": "RATE_LIMIT_EXCEEDED"
  },
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Request a higher quota limit.",
        "url": "https://cloud.google.com/docs/quota#requesting_higher_quota"
      }
    ]
  }
]
, rateLimitExceeded (SQLSTATE HV000)
```

240 is already the maximum for this API so we cannot increase this quota: `ERROR: (gcloud.alpha.services.quota.create) FAILED_PRECONDITION: The consumer override value can only be set between 0 to 240.`

Is there any way to customize the way steampipe handle these rate limit ? Is there any exponential back-off management that could be customize ?

I'm not sure if https://steampipe.io/docs/reference/env-vars/steampipe_max_parallel (setting it to 1, the documentation does not show default value) could affect this throttle management.

**Steampipe version (`steampipe -v`)**
```plain
steampipe --version
Steampipe v0.19.1
```

**Plugin version (`steampipe plugin list`)**
```plain
steampipe plugin list
hub.steampipe.io/plugins/turbot/gcp@latest = 0.33.1
```

**To reproduce**
Execute a query that list GCP projects with a lot of projects

**Expected behavior**
When rate limit occurs, steampipe should exponentially back-off to retry calls

**Additional context**
The request which is always failing is:
```sql
select
    projects.project_number::text,
    projects.project_id,
    projects.title,
    projects.create_time,
    projects.tags ->> 'owner' as "owner",
    ancestors.ancestors
from
    gcp_all.gcp_project as projects
    left outer join gcp_project_ancestors as ancestors on ancestors.project_id = projects.project_id
```

NB: `gcp_project_ancestors` is a custom table on our side

**Comment by cbruno10** [comment]
Hi @vmdude , sorry you're hitting up against the quota limits!

I took a look through some of GCP's docs, like https://cloud.google.com/docs/quota, to see if I could locate when quotas typically reset, but was unsuccessful.

From the GCP error response you included above, it looks like they don't tell us when the rate will reset or approximately how long to wait (in other plugins, like GitHub, we've had some success [implementing retry logic](https://github.com/turbot/steampipe-plugin-github/blob/main/github/errors.go#L22-L37) if we're able to get that information)

Do you have any experience with retrying after quotas are reset, e.g., how long does it take before your query is able to run again or do you know of any doc links that mention timings?

We're interested in improving our backoff retry logic, but often like to understand the retry time periods first as there's a balance of queries eventually finishing vs. queries appearing to hang for several minutes (or more).

Also, can you please provide more info on the types of API calls your `gcp_project_ancestors` table is making and approximately how many projects you have?

Thanks!
