### ISSUE TITLE
GCP tags mapped to labels, resulting only labels data in tags column

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-gcp#442]
**Describe the bug**

We may need to re-visit GCP `tags`, which is mapped to `labels` field; this results in only `labels` data while querying to `tags`. is it desired? 

https://github.com/turbot/steampipe-plugin-gcp/blob/bd7e95e8a3b5fcc0808249476ee41fe0fea54a51/gcp/table_gcp_storage_bucket.go#L203L208

![image](https://user-images.githubusercontent.com/26873346/227198929-f5ec4291-729d-4548-98b3-d45b4b0e311a.png)

GCP Resource 
![image](https://user-images.githubusercontent.com/26873346/227199469-33cd9477-932c-49b4-a6cb-92fe2c8010ea.png)

[Doc Reference](https://cloud.google.com/resource-manager/docs/tags/tags-overview?_ga=2.1298994.-2031933857.1666361508&_gac=1.152566091.1679564624.Cj0KCQjw8e-gBhD0ARIsAJiDsaW_pcvA33zDr8v3ETbAjKAAb1-9KEtYU4kp-JNp1iBgjVEoKazoiN8aAogwEALw_wcB)

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by ParthaI** [comment]
There is no such other API call to get the `Tags` property of storage buckets.

Raised a discussion with GCP GO SDK - https://github.com/googleapis/google-api-go-client/issues/1920
