### ISSUE TITLE
Add table gcp_storage_object

### ISSUE THREAD

**Issue by eric-zhang-aus** [turbot/steampipe-plugin-gcp#459]
Can we add a table (e.g. gcp_storage_object) so we can use Steampipe to query the size of GCS buckets and the number of objects in the buckets within GCP Projects, Thank you!

**Comment by misraved** [comment]
Welcome to Steampipe @eric-zhang-aus and thanks for raising the table request 👍.

Adding API references for the table:
ListConfig - https://cloud.google.com/storage/docs/json_api/v1/objects/list
GetConfig - https://cloud.google.com/storage/docs/json_api/v1/objects/get
