### ISSUE TITLE
table gcp_compute_machine_type not support t2a machine type query

### ISSUE THREAD

**Issue by ahlfors** [turbot/steampipe-plugin-gcp#466]
**Describe the bug**
table gcp_compute_machine_type not support t2a machine type query

**Steampipe version (`steampipe -v`)**
0.20.9

**Plugin version (`steampipe plugin list`)**
v0.40.0

**To reproduce**
execute: 
```
steampipe query  "select * from gcp_compute_machine_type where name = 't2a-standard-2'" --output line
```

**Expected behavior**
Table gcp_compute_machine_type returns t2a-standard-2 machine type records.

**Additional context**
Returns nothing.

**Comment by ahlfors** [comment]
#465 Update zone to us-central1-f to support query t2a machine type to fix this issue

**Comment by rajlearner17** [comment]
@ahlfors Thanks for using Steampipe! 

Nice to see this PR and further testing on it. 
Just quick question on the change you made, is there any GCP doc stating to make this change to `us-central1-f`. This will help.

CC @misraved

**Comment by ahlfors** [comment]
@rajlearner17 After checked gcp official doc, I changed pr to use uc-central1-a, which covered all machine types in this zone : [https://cloud.google.com/compute/docs/regions-zones#quotas](https://cloud.google.com/compute/docs/regions-zones#quotas)

**Comment by rajlearner17** [comment]
@ahlfors Thanks; I hope you mentioned `us-centra1-a` above. thanks for sharing this doc ref

![image](https://github.com/turbot/steampipe-plugin-gcp/assets/26873346/5751e211-e458-439b-a73d-053ca8a118b6)

CC @misraved

**Comment by ahlfors** [comment]
yes, change to us-centra1-a is the fastest fix, as I known.

**Comment by cbruno10** [comment]
If machine types are tied to zones, I wonder if the table should instead use a `ParentHydrate` to list zones, and then list machine types for each zone? If you then run `select * from gcp_compute_machine_type`, then it'd list all machine types for all zones, but you could limit results with `distinct` or `distinct on`.

**Comment by rajlearner17** [comment]
CC @ParthaI

**Comment by cbruno10** [comment]
@ParthaI Thanks for testing, I think your design suggestions look great!

@ahlfors If this design also looks good to you, are you interested in updating your PR to follow this design? Or we can make the updates to the machine type table if you'd find that helpful.

**Comment by rajlearner17** [comment]
@ParthaI Better we raise the PR for this, and @ahlfors can validate the outcome. This will help to close this issue.
