### ISSUE TITLE
Add table gcp_aiplatform_endpoints

### ISSUE THREAD

**Issue by saisirishreddy** [turbot/steampipe-plugin-gcp#470]
**References**
Parity with tables that are provide by CloudQuery
I would be interested in the encryption config, Network config etc.

[gcp_aiplatform_endpoints](https://www.cloudquery.io/docs/plugins/sources/gcp/tables/gcp_aiplatform_endpoints)

https://cloud.google.com/sdk/gcloud/reference/ai/endpoints/describe 

https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.endpoints#Endpoint

https://github.com/cloudquery/cloudquery/blob/main/plugins/source/gcp/resources/services/aiplatform/endpoints.go

**Comment by rajlearner17** [comment]
@saisirishreddy Thanks for raising the issue!

Can you tell us more about your use case for new requested tables?

I hope you are asking for tables for GCP **Vertex AI** for models and endpoints. This will help us to prioritise.

**Comment by saisirishreddy** [comment]
Yes tables for GCP Vertex AI models and endpoints, as there is an uptick AI use cases
