### ISSUE TITLE
Add table gcp_compute_loadbalancer, gcp_firebase_realtime_database, gcp_firebase_cloud_messaging, gcp_container_repository, gcp_iam_service_principal

### ISSUE THREAD

**Issue by vikas-cd** [turbot/steampipe-plugin-gcp#481]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

https://www.linkedin.com/posts/praveensk007_cybersecurity-cisos-cios-activity-7091968284031381505-nWQg?utm_source=share&utm_medium=member_android

I hope this help finding the related service

**Comment by rajlearner17** [comment]
@vikas-cd Thanks for using Steampipe! 🤝 

I appreciate you raised these issues; I request you create separate issues for each. 

Meanwhile, please provide details about your use cases/purpose for Steampipe. This will help us to prioritise. 

You are also welcome to [contribute](https://steampipe.io/docs/develop/writing-your-first-table) if you want to try it.

Cheers!

**Comment by cbruno10** [comment]
@vikas-cd As mentioned in Slack, a GCP load balancer is really just a logical grouping of other GCP resources, like backend services, addresses, etc. A list of resources can be found at https://cloud.google.com/load-balancing/docs/apis.

Is there a particular set of info you're looking to query around load balancers? This will help us prioritize which load balancer related resources we can add as tables. Thanks!

**Comment by bigdatasourav** [comment]
Hi @vikas-cd, we're closing this issue as we have yet to hear back from you; please feel free to re-open if you want to share anything. Thanks!
