### ISSUE TITLE
GCP plugin can not query Asset Inventory

### ISSUE THREAD

**Issue by zhujian0805** [turbot/steampipe-plugin-gcp#484]
Currently there is no table can be used to query Asset Inventory in GCP, can we add that table please?

justification:
i'm looking to get data from the asset inventory for my entire org level projects, by querying each projects one by one with connections, i usually encounter permission issues, so i think asset inventory is better for this purpose.

**Comment by rajlearner17** [comment]
[API Reference](https://github.com/googleapis/google-api-go-client/tree/fd53dcead5d0eda81cfcd480ed1263c668e30510/cloudasset/v1)

**Comment by ParthaI** [comment]
@zhujian0805, I apologize for the delayed response.

We've been investigating the issue you raised. To better assist you and ensure we provide a solution that aligns with your needs, we require some additional information, particularly concerning the specific inventory data you're interested in.

We've reviewed the [GCP API documentation](https://cloud.google.com/asset-inventory/docs/reference/rest/v1/assets/list) and the relevant [GO API](https://pkg.go.dev/google.golang.org/api@v0.139.0/cloudasset/v1), but we couldn't identify a single API call that exclusively returns inventory details of resources.

It would be immensely helpful if you could provide the corresponding Gcloud CLI command you're using along with the expected result. This information will greatly assist us in designing and developing the table effectively. It will help us determine whether a single table can accommodate all the required inventory details or if multiple tables are needed.

Your input is invaluable, and we appreciate your feedback. Thank you for your cooperation!

**Comment by zhujian0805** [comment]
I think that the most common resources would be sufficient. just like listed here: https://hub.steampipe.io/plugins/turbot/gcp/tables

**Comment by bigdatasourav** [comment]
@ParthaI, Could you please try the below API and see if it works?
https://github.com/googleapis/google-api-go-
client/blob/fd53dcead5d0eda81cfcd480ed1263c668e30510/cloudasset/v1/cloudasset-gen.go#L4599C6-L4599C24

**Comment by bigdatasourav** [comment]
https://cloud.google.com/asset-inventory/docs/reference/rest/
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_asset_folder_feed

**Comment by ParthaI** [comment]
Hello @zhujian0805,

I hope this message finds you well. We are excited to inform you that we have introduced a new table named `gcp_cloud_asset_inventory`. In relation to this, we have created a [Pull Request (PR)](https://github.com/turbot/steampipe-plugin-gcp/pull/532) addressing this specific issue.

Your feedback would be immensely valuable to us. We would greatly appreciate it if you could take some time to test the changes in the PR branch and share your thoughts on whether it aligns with your requirements.

For your convenience, here are the steps to test out the code changes:
- Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-gcp.git`
- Change to the directory: `cd steampipe-plugin-gcp`
- Switch to the relevant branch: `git checkout issue-484`
- Execute the command: `make`
- Proceed to query the table

Thank you so much for your ongoing cooperation and support. Your input is incredibly important to us.
