### ISSUE TITLE
GCP Tags should not be copied from labels

### ISSUE THREAD

**Issue by ssuvasanth** [turbot/steampipe-plugin-gcp#540]
**Describe the bug**
GCP 'tags' field should not be copied from 'labels' field

**Steampipe version (`steampipe -v`)**
Steampipe v0.21.1

**Plugin version (`steampipe plugin list`)**
0.47.0

**To reproduce**
1. Add tags to storage buckets in gcp
2. Run the following query in steampipe:
`select tags,name,labels from gcp_0c50f083.gcp_storage_bucket`

**Expected behavior**
Added tags should appear in query result
But the current behaviour is that tags get copied from labels and hence labels appear in tags  result when labels are added.

**Additional context**
[gcp link](https://cloud.google.com/resource-manager/docs/tags/tags-overview#tags_and_labels)

https://github.com/turbot/steampipe-plugin-gcp/blob/main/gcp/table_gcp_storage_bucket.go#L205

`
{
				Name:        "tags",
				Description: ColumnDescriptionTags,
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("Labels"),
},
`

**Comment by misraved** [comment]
Welcome to Steampipe @ssuvasanth and thanks for raising this issue 👍 !!

This looks like a bug and possibly exists in a lot of tables.

We will analyze the document that you provided and the data the APIs return and make corresponding changes to the affected tables soon 👍.

**Comment by ugirirajan** [comment]
@misraved The same issue is there in gcp_project table. Lables are copied to tags.

**Comment by bigdatasourav** [comment]
As of now, Storage [APIs](https://cloud.google.com/storage/docs/json_api/v1/buckets/list) do not provide the assigned tag information.

The tag [API](https://cloud.google.com/resource-manager/reference/rest/v3/tagBindings/list) is available under resource-manager. It should be a separate table https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/tags_tag_binding.
But as per the test, it does not support storage buckets yet.
