### ISSUE TITLE
gcp_cloudfunctions_function is missing some of the column values.

### ISSUE THREAD

**Issue by ashutoshmore658** [turbot/steampipe-plugin-gcp#579]
**Description of  the bug** 

After fixing the plugin for fetching `GEN-2 ` cloud functions from vpc, `gcp_cloudfunctions_function`  table for gcp plugin is missing some column values. They are following below.
1. Status
2. Run Time
3. Available Memory
4. Build Id
5. Entry Point
6. Https Triggers
7. Ingress Settings
8. Max Instances
9. Service Account Email
10. Source Upload URL
11. Timeout

**Steampipe version**
`Steampipe v0.22.2`

**GCP Plugin version**
`GCP Plugin v0.51.1`

**To reproduce**
We can reproduce this issue by simply querying GCP Cloud Functions :
> steampipe query
> select * from gcp.gcp_cloudfunctions_function

**Expected behavior**
It is expected that all mentioned columns are populated when querying `GCP Cloud Functions`, both for `GEN-1` and 
`GEN-2` Cloud Functions.

**Additional context**
Images which proves this issue.
![Screenshot from 2024-05-12 21-45-05](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/e39d508b-0d4b-4805-80e4-d73a9262b68a)
![Screenshot from 2024-05-12 21-48-12](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/abd91cac-9827-4283-a5bd-318dd96f62cd)
![Screenshot from 2024-05-12 21-47-49](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/d4072544-b5f2-4cc9-85a1-064ab7b9ef22)
![Screenshot from 2024-05-12 21-47-22](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/413dd6aa-3ec5-40cd-a2e2-b647b33b6f7e)
![Screenshot from 2024-05-12 21-46-50](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/2f56ee22-f64d-49b7-aa35-efc465c578d9)
![Screenshot from 2024-05-12 21-46-31](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/16cb6997-e309-4f69-9bc9-f5e639b6836c)
![Screenshot from 2024-05-12 21-46-00](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/1704cc94-7cf3-4b07-bc39-9e31d5ceb0a1)
![Screenshot from 2024-05-12 21-45-41](https://github.com/turbot/steampipe-plugin-gcp/assets/101464287/7e03585d-1936-4b6d-9f09-9937ad9d28f9)

**Comment by ashutoshmore658** [comment]
@misraved  If you could please allocate this issue to me, as I know how to resolve this issue.

**Comment by ashutoshmore658** [comment]
@ParthaI  Thank you, raising the fix asap.

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-gcp/pull/590
