### ISSUE TITLE
The column value for `project` is always null for the table `gcp_alloydb_cluster`

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-gcp#616]
**Describe the bug**
The `project` column in the `gcp_alloydb_cluster` table consistently returns null values. This issue affects the ability to accurately query and filter data based on the project column, leading to incomplete or incorrect query results.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
select project, name, region from gcp_alloydb_cluster;

**Expected behavior**
N/A

**Additional context**
N/A

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-gcp/pull/617
