### ISSUE TITLE
Add table gcp_iam_user

### ISSUE THREAD

**Issue by AbhinavCSY** [turbot/steampipe-plugin-gcp#618]
**References**
Can we get the list of GCP IAM USERS in a table if it exists can we know which table to look into?

**Comment by ParthaI** [comment]
Hi @AbhinavCSY, I am closing this issue as there is no direct API to retrieve IAM user details. However, you can obtain user details using the `gcp_iam_policy` table. For further information, please refer to the related discussion thread in the community channel: https://turbot-community.slack.com/archives/C01UECB59A7/p1721384054791709

Please feel free to reopen this issue or create a new one if you encounter any further problems.

Thanks!

**Comment by AbhinavCSY** [comment]
Sure, I understood the problem here.
